swagger: "2.0"
info:
  title: "User Login"
  description: "Endpoint to authenticate user"
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"
parameters:
  - name: body
    in: body
    required: true
    schema:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
responses:
  200:
    description: "Access token generated successfully"
  401:
    description: "Invalid credentials"
