swagger: "2.0"
info:
  title: "Protected Route"
  description: "Endpoint that requires authentication"
  version: "1.0.0"
securityDefinitions:
  JWT:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "JWT token"
responses:
  200:
    description: "Protected route accessed successfully"
  401:
    description: "Missing or invalid JWT token"
